/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package java238;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    boolean bool = true;
    @Test public void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull("app should have a greeting", bool);
    }
}
