package java238;

import ch.bailu.gtk.adw.*;
import ch.bailu.gtk.adw.ApplicationWindow;
import ch.bailu.gtk.adw.HeaderBar;
import ch.bailu.gtk.gio.ApplicationFlags;
import ch.bailu.gtk.gio.File;
import ch.bailu.gtk.gtk.*;
import ch.bailu.gtk.gtk.Application;
import ch.bailu.gtk.type.CPointer;
import ch.bailu.gtk.type.Strs;
import java238.widgets.AutoPicker;
/*
 * This Java source file was generated by the Gradle 'init' task.
 */

public class App {
    public static AutoPicker picker;
    public static Application app;
    public static ApplicationWindow window;
    public static Label label;

    public static void init() {
    }

    public static void onStartup() {
        StyleManager.getDefault().setColorScheme(ColorScheme.FORCE_LIGHT);
    }

    public static void main(String[] args) {
        init();
        Adw.init();
        
        app = new Application("org.frc238.autoBuilder", ApplicationFlags.FLAGS_NONE);
        picker = new AutoPicker();
        app.onStartup(App::onStartup);
        app.onActivate(() -> {
            var header = new HeaderBar();
            var toggleFlap = new Button();
            toggleFlap.onClicked(picker::onOpenClicked);
            header.packStart(toggleFlap);
            window = new ApplicationWindow(app);
            window.setDirection(Orientation.VERTICAL);
//            window.setContent(header);

            Box vbox = new Box(Orientation.VERTICAL, 0);
            Box hbox = new Box(Orientation.HORIZONTAL, 0);
            hbox.append(picker.flap);
            vbox.append(header);
            vbox.append(hbox);
            window.setDefaultSize(600, 800);

            window.setContent(vbox);

            window.present();
        });
        app.run(args.length, new Strs(args));

    }
}